# fly.toml app configuration file generated for finance-dashboard-server-autumn-moon-5741 on 2025-03-24T10:29:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finance-dashboard-server-autumn-moon-5741'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
